# Generated by Django 2.2.9 on 2020-01-25 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=35)),
                ('telephone', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('descriptions', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Status_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('color', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Статус клиента',
                'verbose_name_plural': 'Статусы клиентов',
            },
        ),
        migrations.CreateModel(
            name='Task_Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('data_begin', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_end', models.DateTimeField()),
                ('status_task', models.CharField(choices=[('DO', 'Выполнено'), ('PL', 'Заполанирована'), ('CA', 'Отменено'), ('MO', 'Перенесено')], default='DO', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача менеджеру',
                'verbose_name_plural': 'Задачи менеджеру',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('data_edit', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
        migrations.CreateModel(
            name='Comment_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Коментарий о клиенте',
                'verbose_name_plural': 'Коментарии о клиентах',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='status_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Status_client'),
        ),
    ]
