# Generated by Django 2.2.8 on 2019-12-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='descriptions',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='status_client',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
