# Generated by Django 2.2.9 on 2020-01-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20191214_2352'),
        ('clients', '0003_auto_20191215_0109'),
    ]

    operations = [
    ]
