# Generated by Django 2.2.9 on 2020-01-25 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorygGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('isHealth', models.BooleanField(default=False, verbose_name='Здоровая пища')),
                ('isAlhogol', models.BooleanField(default=False, verbose_name='Содержит спирт')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('price', models.FloatField(verbose_name='Цена по прайсу')),
                ('isHealth', models.BooleanField(default=False, verbose_name='Здоровая пища')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.categorygGoods', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда>',
            },
        ),
    ]
