# Generated by Django 2.2.8 on 2019-12-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда>'},
        ),
        migrations.AlterField(
            model_name='categoryggoods',
            name='isAlhogol',
            field=models.BooleanField(default=False, verbose_name='Содержит спирт'),
        ),
    ]
