# Generated by Django 2.2.8 on 2019-12-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_goodsbyorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsbyorder',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='Comment',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
