# Generated by Django 3.0 on 2019-12-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191214_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timeОfdelivery',
            field=models.DateField(null=True),
        ),
    ]
